### ISSUE TITLE
[gogo-genproto] any chance we can delete this repo?

### ISSUE THREAD

**Issue by ldemailly** [istio/gogo-genproto#7]
replace it with something in either vendor-istio or api ?

**Comment by kyessenov** [comment]
Please do not delete this repository. It's a dependency of go-control-plane, which itself is a dependency of a number of projects. I'm migrating some protos to where they belong (e.g. googleapis) but some other ones simply do not have an alternative (e.g. opencensus).

**Comment by kyessenov** [comment]
Closing, and reopen once opencensus and prometheus vendor gogo-generated protos.
